# Generated by Django 3.0 on 2020-06-06 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=512)),
                ('short_url', models.CharField(max_length=20)),
                ('timestap', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
