# Generated by Django 3.0 on 2020-06-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
