# Generated by Django 3.0.7 on 2020-08-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_remove_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
