# Generated by Django 3.0.7 on 2020-08-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_auto_20200810_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
