# Generated by Django 4.1.1 on 2022-09-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("link", "0009_alter_url_options_alter_url_table")]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        )
    ]
